artifacts_root: experiments/artifacts


data_ingestion:
  root_dir: experiments/artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1xb_Q9FiQ9X33h99R7LTkdDeSXG_E9hty/view?usp=drive_link
  local_data_file: experiments/artifacts/data_ingestion/data.zip
  unzip_dir: experiments/artifacts/data_ingestion


prepare_base_model:
  root_dir: experiments/artifacts/prepare_base_model
  base_model_path: experiments/artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: experiments/artifacts/prepare_base_model/base_model_updated.h5


training:
  root_dir: experiments/artifacts/training
  trained_model_path: experiments/artifacts/training/model.h5